# Site settings
title: Web Afternoon
email: your-email@domain.com
tagline: For today, you’re the user.
subheader: And the product is great conversations with people like you who want to design a better web.
description: Let’s talk UX. We designed this event with you in mind. We dream in wireframes, too. And so do the thought leaders waiting to mingle with you. Their talks are practical--real world tips and tricks you can put into action immediately. There’s no fluff. You’ll leave equipped and inspired to get back to doing what you do best.
panel: Bookended by talks from pre-eminent UXers, we'll be presenting a panel of four thought leaders you can relate to. They do what you do every day and have a wealth of knowledge to share. Bring your questions and get ready to participate!
brunch: Want to get really up close and personal? Purchase a VIP pass to enjoy an exclusive brunch with your UX hero and get reserved seating for the afternoon of talks. There are only 9 seats at each of the five tables--and they're first come, first served--so buy your ticket now to make sure your name's on the list.
what_to _expect: Four speakers and a panel of thought leaders bring the latest and greatest in UX that's relevant to you. The afternoon will give you the opportunity to connect with others interested in the same topics as you. At the end of it all we'll mingle together and indulge in a libation or two. 
We minimize the fluff to focus on providing quality content from people in the know, at a price you can afford. Every penny from our events goes straight back to help local groups and meet-ups you love. We've generated thousands of dollars so far for Web and technology-focused groups. And we're just getting started.
Web Afternoon is fast-paced and designed to spur conversations, because that's how ideas are born.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://webafternoon.com" # the base hostname & protocol for your site
twitter_username: webafternoon

# Build settings
markdown: kramdown
