# Site settings
title: Web Afternoon
email: events@ninelabs.com
description: Events for People Who Love the Web
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://webafternoon.com" # the base hostname & protocol for your site
twitter_username: webafternoon

# Build settings
markdown: kramdown
exclude: [vendor]
